### ISSUE TITLE
how to build mp_pose_tracking.aar?

### ISSUE THREAD

**Issue by 278156754** [LeeJeongHwi/Mediapipe_pose_Tracking_AAR_example#2]
Hi LeeJeongHwi,
I build mp_pose_tracking.aar following https://google.github.io/mediapipe/getting_started/android_archive_library.html，when i replace mp_pose_tracking.aar in your example and run in mobile, it crashed. The log is as follow,
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/79309425/123195477-d1a2d280-d4da-11eb-9be7-4a2faee30daa.png">

and my build script is 
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_pose_tracking",
    calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps", "//mediapipe/gpu:image_frame_to_gpu_buffer_calculator"],
)

can you show me your build script for mp_pose_tracking.aar?
Thanks in advance.

**Comment by 278156754** [comment]
sorry， the calculator is wrong, and the correct is as follow
 calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps", "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator"],

**Comment by LeeJeongHwi** [comment]
Hi @278156754 , I'm glad you solved the issue.

if that calculator code is also error, try using this script :) 

```
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mp_pose_tracking_aar",
    calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps"],
)

bazel build -c opt --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --fat_apk_cpu=arm64-v8a,armeabi-v7a --linkopt="-s" //mediapipe/examples/android/src/java/com/google/mediapipe/apps/[BUILD File Dir]:mp_pose_tracking_aar

```

Thank you
