### ISSUE TITLE
Manipulation Stick Figure

### ISSUE THREAD

**Issue by taatiq882** [LeeJeongHwi/Mediapipe_pose_Tracking_AAR_example#3]
Hi, I want to ask where I can access the pose landmarks and how can I manipulate stick figure.

**Comment by LeeJeongHwi** [comment]
hello! @taatiq882 
please refer to this [Line](https://github.com/LeeJeongHwi/Mediapipe_pose_Tracking_AAR_example/blob/3feb4549b6409812cdad31034fe3f0026b87c56e/app/src/main/java/com/example/myapplication/MainActivity.java#L299)
that extract coordinate (x,y,visibility)

Thank you

**Comment by taatiq882** [comment]
Thanks for your prompt reply. Secondly if you could guide me about manipulation of stick figure. Like how can I show only specific points ? Lets say I just want to show the nose point. How this can be achieved ?

**Comment by LeeJeongHwi** [comment]
Unfortunately, I tried the question that you asked before, but I failed. Sorry.

it would be good for you to check [Graph](https://viz.mediapipe.dev/demo/pose_tracking) of [Mediapipe Official Page](https://google.github.io/mediapipe/solutions/pose.html#javascript-solution-api) and this [Issue](https://github.com/google/mediapipe/issues/1849).

- Suggestion 1
Why don't you take to look at the pose_landmarks.pbtxt in above graph, modify the node of graph and then rebuild it?

Thank you.
